/* This file was generated by syncqt. */
#ifndef QT_QTSCXML_VERSION_H
#define QT_QTSCXML_VERSION_H

#define QTSCXML_VERSION_STR "5.15.10"

#define QTSCXML_VERSION 0x050F0A

#endif // QT_QTSCXML_VERSION_H
