/* This file was generated by syncqt. */
#ifndef QT_QTSENSORS_VERSION_H
#define QT_QTSENSORS_VERSION_H

#define QTSENSORS_VERSION_STR "5.15.10"

#define QTSENSORS_VERSION 0x050F0A

#endif // QT_QTSENSORS_VERSION_H
